### ISSUE TITLE
Rename "given" to "the"

### ISSUE THREAD

**Issue by shamrin** [witheve/rfcs#8]
> For example, in `count[given: cell, per: player]` we group by player, which returns two values: the count of cells marked by player X and those marked by O. This can be read “count the cells per player”. 

http://incidentalcomplexity.com/2016/08/11/tic-tac-toe/

What about renaming `given` to `the`? 

```
count[the: cell, per: player]
```

**Comment by cmontella** [comment]
What I'm about to say is past the edge of where Eve is right now, so the following won't work at the moment, but it's how things could work.

One thing that's nice about Eve is that you could potentially rename attributes to something that makes sense to you. This would allow a complete French or Arabic localizations of Eve, for example, where absolutely no English is required.

Recall that the function call syntax is really sugar for `[#count #function given per]`. So you could possibly rename `given` like so:

```
  match 
    count = [#count #function the]
  bind
    count.given := the
```

This will have obvious issues with distributing your code. One way we might mitigate that is by distributing a compatibility bag with your code that has these translations and customizations built in.

While this currently doesn't work, can you see the idea? Basically, I think in terms of argument names and such they'll make sense to some people and others will have an issue no matter what we choose. This mechanism would give you complete control to define things the way you want to.

**Comment by cmontella** [comment]
@shamrin I'm going to close this guy, assuming that the above solution is adequate to support your use case. If you want to further discuss, we can reopen.
